name: bygg
on:
  push:
    branches:
      - 'main'

env:
  IMAGE_ID: ghcr.io/navikt/familie-bygg-eksperimentering:${{ github.run_id }}
  IMAGE: ghcr.io/navikt/familie-bygg-eksperimentering:v${{ github.sha }}
  IMAGE_LATEST: ghcr.io/navikt/familie-bygg-eksperimentering:latest
jobs:
  deploy-to-prod:
    name: Bygg
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Legg på git-tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ github.run_id}}',
              sha: context.sha
            })
      - name: Bygg Docker image
        run: |
          docker build -t ${IMAGE} -t ${IMAGE_LATEST} -t ${IMAGE_ID} .
      - name: Push Docker image med versjonstag
        run: docker push ${IMAGE}
      - name: Push Docker image med 'latest' tag
        run: docker push ${IMAGE_LATEST}