name: bygg
on:
  workflow_dispatch:

env:
  IMAGE: ghcr.io/navikt/familie-bygg-eksperimentering:${{ github.ref_name }}
jobs:
  deploy-to-prod:
    name: Bygg
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pull Docker image med versjonstag
        run: docker pull ${IMAGE}
#      - name: Deploy til prod-gcp
#        uses: nais/deploy/actions/deploy@v1
#        env:
#          APIKEY: ${{ secrets.GITHUB_ACCESS_TOKEN }}
#          CLUSTER: prod-gcp
#          RESOURCE: .deploy/nais/app-prod.yaml