name: bygg
on:
  workflow_dispatch:

env:
  IMAGE: ghcr.io/navikt/familie-bygg-eksperimentering:${{ github.ref_name }}
  IMAGE_PREVIOUS: ghcr.io/navikt/familie-bygg-eksperimentering:previous
  IMAGE_LATEST: ghcr.io/navikt/familie-bygg-eksperimentering:latest
jobs:
  deploy-to-prod:
    name: Bygg
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/checkout@v2
      - name: Pull Docker image med versjonstag
        run: docker pull ${IMAGE}